<?php

/**
 * @file
 * Primary module hooks for Redneck Karaoke module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function redneck_karaoke_user_format_name_alter(&$name, $account) {
  $member = \Drupal\user\Entity\User::load($account->id());

  // Make sure that this user has all elements set.
  if ($member->hasField('field_display_name') && !empty($member->field_display_name->value)) {
    $name = $member->field_display_name->value;
  }
}
